// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EventDTO is an autogenerated mock type for the EventDTO type
type EventDTO struct {
	mock.Mock
}

// NewEventDTO creates a new instance of EventDTO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventDTO(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventDTO {
	mock := &EventDTO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
