// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	query "github.com/jperdior/recordari-kit/query"
	mock "github.com/stretchr/testify/mock"
)

// Query is an autogenerated mock type for the Query type
type Query struct {
	mock.Mock
}

// Type provides a mock function with given fields:
func (_m *Query) Type() query.Type {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 query.Type
	if rf, ok := ret.Get(0).(func() query.Type); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(query.Type)
	}

	return r0
}

// NewQuery creates a new instance of Query. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *Query {
	mock := &Query{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
