name: Create Release Tag

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release Tag
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')" # Create a tag based on the current timestamp
        git tag $TAG_NAME
        git push origin $TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: write  # Grant permission to write to the repository contents (push tags)
